springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.use-root-path=true
springdoc.swagger-ui.path=/swagger-ui.html

app.swagger.server-url=${APP_SWAGGER_SERVER_URL:http://localhost:8086/api}
