package com.notificacao_api.enums;

public enum CodigoErroEnvio {
    WHATSAPP_NUMERO_INVALIDO,
    WHATSAPP_RESTRICAO_463,
    WHATSAPP_NAO_CONECTADO,
    WHATSAPP_SESSAO_NAO_INICIADA,
    GATEWAY_INDISPONIVEL,
    CONFIGURACAO_INDISPONIVEL,
    MENSAGEM_DUPLICADA,
    AGUARDANDO_PROTECAO,
    GENERICO
}
