package com.notificacao_api.enums;

public enum WebhookEvento {
    NOTIFICACAO_CRIADA,
    NOTIFICACAO_ENVIADA,
    NOTIFICACAO_ENTREGUE,
    NOTIFICACAO_LIDA,
    NOTIFICACAO_FALHOU,
    CONTATO_BLOQUEADO,
    WHATSAPP_DESCONECTADO,
    WHATSAPP_QR_ATUALIZADO
}
